modLoader="javafml"
loaderVersion="*"
license="MIT License"
logoFile="integrated_mining.png"
logoBlur=false

[[mods]]
modId="integrated_mining"
displayName="Integrated Mining"
version="1.1.0"
description='''
Compatibility patch for several mining-related mods
'''
[[dependencies.integrated_mining]]
modId="minecraft"
versionRange="1.21.1"
ordering="NONE"
side="BOTH"

[[dependencies.integrated_mining]]
modId="blueprint"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.integrated_mining]]
modId="st_gsoc"
type="incompatible"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.integrated_mining]]
modId="galosphere"
type="optional"
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.integrated_mining]]
modId="spelunkery"
type="optional"
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.integrated_mining]]
modId="oreganized"
type="optional"
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.integrated_mining]]
modId="caverns_and_chasms"
type="optional"
versionRange="*"
ordering="AFTER"
side="BOTH"
